### ISSUE TITLE
Add support for deleting entries by Merging configs.

### ISSUE THREAD

**Issue by phochste** [dsheroh/Config-Onion#12]
E.g.

File1

    foo:
       bar: test
       rest: ok

File2

    foo:
       bar: null | !!DELETE!! | whatever

Merging file1 and file2 will give:

    foo:
      rest: ok

**Comment by dsheroh** [comment]
Feature added in Config::Onion 1.007, which should appear on CPAN shortly.

Values of "!DELETE!" in unblessed hashes will cause their corresponding keys to be deleted.  Arrays are ignored because they have to be completely rewritten to change them anyhow and blessed references are ignored to prevent breaking objects by violating encapsulation.
